`timescale 1ns/1ps
`default_nettype none

import m68882_cir_pkg::*;

// MC68882 CIR register storage -- Phase 2.
//
// Plain read/write storage for every writable/read-writable CIR, with
// correct per-register width and the real D16-D31 data-lane placement
// (Section 9.8's own explicit note: every 16-bit CIR always lives on
// D16-D31, regardless of port size or the register's own odd/even
// address -- "to eliminate the need for on-chip multiplexors"). 32-bit
// CIRs (Operand/Instruction-Address/Operand-Address) span the full
// D31-D0.
//
// Scope boundary, matching m68882_cir_pkg.sv's own documented boundary:
// 8-bit-port operation needs a genuine multi-cycle byte-sequencing state
// machine to transfer a 16/32-bit CIR value one byte at a time (Section
// 10.1's own "if a port size of 8 or 16 bits is selected, multiple
// cycles to transfer the entire operand"). NOT implemented here -- this
// project's real use cases (the companion MH030 68030 project, or any
// reasonable third-party 68030/68020 host) are all 32-bit-bus systems.
// A 16-bit port accessing a 32-bit CIR is ALSO not yet implemented for
// the same multi-cycle reason -- only same-or-wider port-vs-register-
// width combinations work correctly today (32-bit port with any CIR;
// 16-bit port with a 16-bit CIR).
//
// Response/Save/Register-Select are real registers on the chip but their
// CONTENT is generated by protocol/arithmetic logic that doesn't exist
// until Phase 3/4/5 -- reads return zero here as an explicit stub, not a
// silent wrong answer to be discovered later. Control/Command/Condition/
// Instruction-Address are write-only on real silicon (no read path
// exists in the case statement below; a read of one returns the
// `default` zero, an unspecified-on-real-silicon case).

module m68882_cir (
    input  logic      clk_4x,
    input  logic      rst_n,

    input  logic      cyc_ack,     // this cycle's DSACK has asserted
    input  logic      cyc_write,
    input  cir_sel_t  cyc_sel,

    input  logic [31:0] d_in,
    output logic [31:0] d_out,
    output logic         d_oe        // 1 while this module should drive d_out
);

    logic [15:0] control_r;
    logic [15:0] restore_r;
    logic [15:0] command_r;
    logic [15:0] condition_r;
    logic [31:0] operand_r;
    logic [31:0] instraddr_r;
    logic [31:0] opndaddr_r;

    wire write_strobe = cyc_ack && cyc_write;
    wire read_strobe  = cyc_ack && !cyc_write;

    // BUG FOUND BUILDING PHASE 2 (real, not a testbench artifact): a host
    // negates AS#/DS# and releases the data bus the instant IT decides the
    // cycle is over, but this chip's own synchronized view of that
    // negation lags by up to 2 clk_4x ticks (the 2-stage synchronizer,
    // m68882_sync). write_strobe is a LEVEL, not a pulse -- it stays
    // asserted for those extra ticks. A naive `if (write_strobe)` write
    // (as this module originally had) re-latches d_in on every one of
    // those extra ticks, and by then the host has already tri-stated the
    // bus -- the just-written value gets overwritten with X/Z. Section
    // 10.4.3's own wording ("an asserted pulse occurs on DS, the FPCP
    // responds by... latching the value") already implies a one-shot
    // latch, not continuous re-sampling; edge-detecting write_strobe's
    // own rising edge is both the fix and the more faithful model.
    logic write_strobe_prev_r;
    always_ff @(posedge clk_4x or negedge rst_n)
        if (!rst_n) write_strobe_prev_r <= 1'b0;
        else        write_strobe_prev_r <= write_strobe;

    wire write_pulse = write_strobe && !write_strobe_prev_r;

    always_ff @(posedge clk_4x or negedge rst_n) begin
        if (!rst_n) begin
            control_r   <= '0;
            restore_r   <= '0;
            command_r   <= '0;
            condition_r <= '0;
            operand_r   <= '0;
            instraddr_r <= '0;
            opndaddr_r  <= '0;
        end else if (write_pulse) begin
            case (cyc_sel)
                CIR_CONTROL:   control_r   <= d_in[31:16]; // 16-bit CIR, D16-D31 lane
                CIR_RESTORE:   restore_r   <= d_in[31:16];
                CIR_COMMAND:   command_r   <= d_in[31:16];
                CIR_CONDITION: condition_r <= d_in[31:16];
                CIR_OPERAND:   operand_r   <= d_in[31:0];
                CIR_INSTRADDR: instraddr_r <= d_in[31:0];
                CIR_OPNDADDR:  opndaddr_r  <= d_in[31:0];
                default: ; // Response/Save/Register-Select/reserved: no write path
            endcase
        end
    end

    always_comb begin
        d_out = 32'h0000_0000;
        d_oe  = read_strobe;
        case (cyc_sel)
            CIR_RESPONSE:  d_out = 32'h0000_0000; // Phase 3 stub -- real Response
                                                   // primitive generation doesn't
                                                   // exist yet
            CIR_SAVE:      d_out = 32'h0000_0000; // Phase 3/5 stub
            CIR_RESTORE:   d_out = {restore_r, 16'h0000};
            CIR_OPERAND:   d_out = operand_r;
            CIR_REGSELECT: d_out = 32'h0000_0000; // Phase 3 stub
            CIR_OPNDADDR:  d_out = opndaddr_r;     // R/W but dead/unimplemented on
                                                    // real silicon -- modeled as
                                                    // plain storage anyway, never
                                                    // actually referenced by the
                                                    // real protocol
            default:       d_out = 32'h0000_0000;  // write-only CIRs (Control/
                                                    // Command/Condition/Instruction-
                                                    // Address) and reserved offsets:
                                                    // unspecified on real silicon
        endcase
    end

endmodule
