`timescale 1ns/1ps
`default_nettype none

// MC68882 Top Level -- Phase 1 skeleton.
//
// Pin-compatible port list (CLAUDE.md's own Pin List table), wired here to
// two internal blocks: m68882_sync (one synchronizer instance per
// asynchronous host input) and m68882_biu (Phase 1's own async-cycle-
// detect + DSACK skeleton). No CIR register file yet -- see plan.md
// Phase 2.
//
// Clock: clk_4x is this chip's OWN independent internal clock, already
// multiplied to 4x its own external CLK rate -- supplied by the
// testbench/environment. This mirrors the sibling MH030 project's
// identical `clk_4x`-port convention (m68030_top.sv takes the same shape
// of port, for the same reason: a literal on-chip PLL/clock-multiplier is
// out of scope for a cycle-accurate simulation model). This is a wholly
// separate clock domain from any host CPU's own clk_4x -- never derived
// from or synchronized to it, per the user's own explicit requirement
// that this chip have its own clock, independent of any host CPU's.

module m68882_top (
    input  logic        clk_4x,
    input  logic        rst_n,      // RESET# pin

    // ─────────────────────────────────────────────────────────────────
    // Pin-compatible external interface (CLAUDE.md Pin List)
    // ─────────────────────────────────────────────────────────────────
    input  logic [4:0]  a,          // A0-A4, CIR select (no on-chip FC/CPU-space decode)
    inout  wire  [31:0] d,          // D0-D31
    input  logic        size_n,     // SIZE#, port-width strap
    input  logic        as_n,       // AS#
    input  logic        cs_n,       // CS# -- generated by external glue logic, not this chip
    input  logic        rw,         // R/W
    input  logic        ds_n,       // DS#
    output logic        dsack0_n,   // DSACK0#
    output logic        dsack1_n,   // DSACK1#
    inout  wire         sense_n     // SENSE# (optional, unused Phase 1)
);

    // ── Synchronize every host-driven input into this chip's own clk_4x
    // domain (CLAUDE.md: "Every bus input must be synchronized") ──────────
    logic       as_n_s, ds_n_s, cs_n_s, rw_s, size_n_s;
    logic [4:0] a_s;

    m68882_sync #(.WIDTH(1)) u_sync_as   (.clk_4x, .rst_n, .d(as_n),   .q(as_n_s));
    m68882_sync #(.WIDTH(1)) u_sync_ds   (.clk_4x, .rst_n, .d(ds_n),   .q(ds_n_s));
    m68882_sync #(.WIDTH(1)) u_sync_cs   (.clk_4x, .rst_n, .d(cs_n),   .q(cs_n_s));
    m68882_sync #(.WIDTH(1)) u_sync_rw   (.clk_4x, .rst_n, .d(rw),     .q(rw_s));
    m68882_sync #(.WIDTH(1)) u_sync_size (.clk_4x, .rst_n, .d(size_n), .q(size_n_s));
    m68882_sync #(.WIDTH(5)) u_sync_a    (.clk_4x, .rst_n, .d(a),      .q(a_s));

    logic cyc_active, cyc_write;

    m68882_biu u_biu (
        .clk_4x,
        .rst_n,
        .as_n_s,
        .ds_n_s,
        .cs_n_s,
        .rw_s,
        .dsack0_n,
        .dsack1_n,
        .cyc_active,
        .cyc_write
    );

    // a_s/size_n_s are captured and available for Phase 2's own CIR
    // register file (which CIR is selected, and its real bus width) --
    // deliberately unused past this point in Phase 1, since no register
    // file exists yet to consume them.

    // No CIR register file yet (Phase 2) -- data bus stays tri-stated.
    assign d = 32'bz;
    assign sense_n = 1'bz;

endmodule
