`timescale 1ns/1ps
`default_nettype none

import m68882_cir_pkg::*;

// MC68882 CIR register storage -- Control/Restore/Save/Instruction-
// Address/Operand-Address only (Phase 2, Phase 5/6 territory for the
// Restore/Save/Instruction-Address dialogs themselves). Response,
// Command, Condition, Operand, and Register Select moved to
// m68882_proto.sv (Phase 3) -- those five are the ones with genuine
// instruction-dialog protocol behind them; this module keeps the
// simpler, still-mostly-storage-only registers.
//
// Correct per-register width and the real D16-D31 data-lane placement
// (Section 9.8's own explicit note: every 16-bit CIR always lives on
// D16-D31, regardless of port size or the register's own odd/even
// address). 32-bit CIRs (Instruction-Address/Operand-Address) span the
// full D31-D0.
//
// Scope boundary, matching m68882_cir_pkg.sv's own documented boundary:
// 8-bit-port operation and a 16-bit port accessing a 32-bit CIR both need
// a genuine multi-cycle byte-sequencing state machine, not implemented
// here -- this project's real use cases (the companion MH030 68030
// project, or any reasonable third-party 68030/68020 host) are all
// 32-bit-bus systems.
//
// Control CIR (Phase 3 simplification, documented in plan.md): modeled
// with the 68881's own unconditional-abort semantic (any write aborts
// whatever dialog is in progress) rather than the 68882's real AB-window-
// vs-XA distinction -- that distinction needs real per-instruction
// abort-window tracking, deferred to Phase 6 alongside the rest of the
// 68882-specific pipelining work. The `abort` output pulses once per
// Control CIR write, consumed by m68882_proto.sv to reset its own dialog
// state.
//
// Restore/Save/Instruction-Address CONTENT is generated by dialog logic
// that doesn't exist until Phase 5/6 -- reads return zero here as an
// explicit stub, not a silent wrong answer to be discovered later.

module m68882_cir (
    input  logic      clk_4x,
    input  logic      rst_n,

    input  logic      cyc_ack,     // this cycle's DSACK has asserted
    input  logic      cyc_write,
    input  cir_sel_t  cyc_sel,

    input  logic [31:0] d_in,
    output logic [31:0] d_out,
    output logic         d_oe,       // 1 while this module should drive d_out
    output logic         abort       // one-tick pulse on every Control CIR write
);

    logic [15:0] restore_r;
    logic [31:0] instraddr_r;
    logic [31:0] opndaddr_r;

    wire write_strobe = cyc_ack && cyc_write;
    wire read_strobe  = cyc_ack && !cyc_write;

    // Phase 2's own write-pulse finding (see git history / CLAUDE.md):
    // write_strobe is a LEVEL that stays asserted a few extra clk_4x
    // ticks past when a real host releases the data bus (synchronizer
    // latency) -- edge-detect it so every write latches exactly once.
    logic write_strobe_prev_r;
    always_ff @(posedge clk_4x or negedge rst_n)
        if (!rst_n) write_strobe_prev_r <= 1'b0;
        else        write_strobe_prev_r <= write_strobe;

    wire write_pulse = write_strobe && !write_strobe_prev_r;

    assign abort = write_pulse && (cyc_sel == CIR_CONTROL);

    always_ff @(posedge clk_4x or negedge rst_n) begin
        if (!rst_n) begin
            restore_r   <= '0;
            instraddr_r <= '0;
            opndaddr_r  <= '0;
        end else if (write_pulse) begin
            case (cyc_sel)
                CIR_RESTORE:   restore_r   <= d_in[31:16]; // 16-bit CIR, D16-D31 lane
                CIR_INSTRADDR: instraddr_r <= d_in[31:0];
                CIR_OPNDADDR:  opndaddr_r  <= d_in[31:0];
                default: ; // CIR_CONTROL handled above (abort only, no storage
                           // needed for Phase 3's own unconditional-abort model)
            endcase
        end
    end

    always_comb begin
        d_out = 32'h0000_0000;
        d_oe  = 1'b0;
        case (cyc_sel)
            CIR_SAVE:      begin d_oe = read_strobe; d_out = 32'h0000_0000; end // Phase 5 stub
            CIR_RESTORE:   begin d_oe = read_strobe; d_out = {restore_r, 16'h0000}; end
            CIR_OPNDADDR:  begin d_oe = read_strobe; d_out = opndaddr_r; end // R/W but
                                                    // dead/unimplemented on real
                                                    // silicon -- modeled as plain
                                                    // storage anyway, never actually
                                                    // referenced by the real protocol
            default: ; // Control/Instruction-Address (write-only) and reserved
                       // offsets: no read path, d_oe stays 0
        endcase
    end

endmodule
