`timescale 1ns/1ps
`default_nettype none

import m68882_cir_pkg::*;
import m68882_apu_pkg::*;

// Phase 4a test: register-to-register FADD/FSUB, driven through the real
// Command CIR dialog (opclass 000) rather than calling m68882_apu_pkg's
// own fp_add_sub task directly -- this confirms the full path (command
// word decode -> APU -> register file write -> FPSR update), not just
// the arithmetic core in isolation.
//
// Test operands are known-good IEEE-754-consistent extended-precision
// bit patterns (Table 3-3's own layout), computed independently in
// Python and cross-checked by hand (1.0, 2.0, 3.0, 0.5, 1.5, -1.0) --
// not generated by this project's own RTL, so this is a genuine
// external check, not a tautology.
//
// FP0-7 are loaded directly via a hierarchical backdoor write (this
// project has no other way to load an EXACT, arbitrary extended-
// precision bit pattern yet -- Phase 3's own opclass 010/011 external-
// transfer dialog is still a raw-bytes stub, not real format
// conversion, so it can't be used to construct a precise test operand
// until Phase 6 lands real conversion).

module m68882_apu_tb;

    logic clk_4x = 1'b0;
    logic rst_n  = 1'b0;

    logic [4:0]  a      = 5'h00;
    logic        size_n = 1'b1;
    logic        as_n   = 1'b1;
    logic        cs_n   = 1'b1;
    logic        rw     = 1'b1;
    logic        ds_n   = 1'b1;
    wire         dsack0_n;
    wire         dsack1_n;
    wire         sense_n;

    logic [31:0] d_drv    = 32'h0;
    logic        d_drv_en = 1'b0;
    wire  [31:0] d = d_drv_en ? d_drv : 32'bz;

    always #5 clk_4x = ~clk_4x;

    m68882_top u_top (
        .clk_4x   (clk_4x),
        .rst_n    (rst_n),
        .a        (a),
        .d        (d),
        .size_n   (size_n),
        .as_n     (as_n),
        .cs_n     (cs_n),
        .rw       (rw),
        .ds_n     (ds_n),
        .dsack0_n (dsack0_n),
        .dsack1_n (dsack1_n),
        .sense_n  (sense_n)
    );

    int pass_count = 0;
    int fail_count = 0;

    task automatic check(input logic cond, input string msg);
        if (cond) begin
            pass_count++;
            $display("PASS: %s", msg);
        end else begin
            fail_count++;
            $display("FAIL: %s", msg);
        end
    endtask

    task automatic run_cycle(
        input  logic [3:0]  sel_a4_a1,
        input  logic        is_write,
        input  logic [31:0] wdata,
        output logic [31:0] rdata
    );
        int wait_ticks;
        @(posedge clk_4x);
        a      = {sel_a4_a1, 1'b1}; // 32-bit port throughout
        rw     = !is_write;
        if (is_write) begin
            d_drv_en = 1'b1;
            d_drv    = wdata;
        end else begin
            d_drv_en = 1'b0;
        end
        cs_n = 1'b0;
        as_n = 1'b0;
        ds_n = 1'b0;

        wait_ticks = 0;
        while (dsack0_n && dsack1_n && wait_ticks < 60) begin
            @(posedge clk_4x);
            wait_ticks++;
        end
        rdata = d;

        @(posedge clk_4x);
        cs_n     = 1'b1;
        as_n     = 1'b1;
        ds_n     = 1'b1;
        d_drv_en = 1'b0;
        repeat (2) @(posedge clk_4x);
    endtask

    function automatic logic [31:0] cmd_word(
        logic [2:0] opclass, logic [2:0] rx, logic [2:0] ry, logic [6:0] ext
    );
        return {opclass, rx, ry, ext, 16'h0};
    endfunction

    // Known-good extended-precision constants (sign|exp15|reserved16|mantissa64)
    localparam logic [95:0] EXT_1_0  = 96'h3fff_0000_8000_0000_0000_0000;
    localparam logic [95:0] EXT_2_0  = 96'h4000_0000_8000_0000_0000_0000;
    localparam logic [95:0] EXT_3_0  = 96'h4000_0000_c000_0000_0000_0000;
    localparam logic [95:0] EXT_0_5  = 96'h3ffe_0000_8000_0000_0000_0000;
    localparam logic [95:0] EXT_1_5  = 96'h3fff_0000_c000_0000_0000_0000;
    localparam logic [95:0] EXT_N1_0 = 96'hbfff_0000_8000_0000_0000_0000;
    localparam logic [95:0] EXT_4_0  = 96'h4001_0000_8000_0000_0000_0000;
    localparam logic [95:0] EXT_6_0  = 96'h4001_0000_c000_0000_0000_0000;
    localparam logic [95:0] EXT_2_25 = 96'h4000_0000_9000_0000_0000_0000;
    localparam logic [95:0] EXT_N3_0 = 96'hc000_0000_c000_0000_0000_0000;
    localparam logic [95:0] EXT_0_25 = 96'h3ffd_0000_8000_0000_0000_0000;

    logic [31:0] rd;

    task automatic load_fp(input int idx, input logic [95:0] val);
        u_top.u_proto.u_regfile.fp_r[idx] = val;
    endtask

    // Phase 6: Command CIR dispatch now REQUIRES the mandatory Instruction
    // Address CIR write next (otherwise proto_violation_r pulses and the
    // dialog never leaves ST_WAIT_IADDR), and every opclass-000 op
    // (FADD/FSUB/FMUL/FDIV/FSQRT/FCMP/FABS/FNEG/FTST/FMOVE) commits only
    // after a genuine multi-cycle APU pipeline latency
    // (m68882_proto.sv's own apu_latency(), Phase 9: real Table 8-3
    // cycle counts -- NONE of these ops are actually zero-cycle on real
    // silicon) -- a fixed "repeat(2)" is no longer enough for any of
    // them. Poll the real pipeline-occupancy registers instead of
    // hardcoding a cycle count.
    task automatic dispatch(input logic [31:0] cmdw);
        logic [31:0] rd2;
        int wait_ticks;
        run_cycle(CIR_COMMAND, 1'b1, cmdw, rd2);
        run_cycle(CIR_INSTRADDR, 1'b1, 32'h0000_2000, rd2);
        wait_ticks = 0;
        while ((u_top.u_proto.slotA_valid_r || u_top.u_proto.slotB_valid_r) && wait_ticks < 1000) begin
            @(posedge clk_4x);
            wait_ticks++;
        end
        repeat (2) @(posedge clk_4x);
    endtask

    // Shares dispatch()'s own drain-wait logic, for a test that dispatched
    // via raw run_cycle calls directly (to observe mid-flight state) and
    // now just needs to wait for the already-in-flight op to commit.
    task automatic wait_ticks_apu_drain();
        int wait_ticks;
        wait_ticks = 0;
        while ((u_top.u_proto.slotA_valid_r || u_top.u_proto.slotB_valid_r) && wait_ticks < 1000) begin
            @(posedge clk_4x);
            wait_ticks++;
        end
        repeat (2) @(posedge clk_4x);
    endtask

    initial begin
        repeat (4) @(posedge clk_4x);
        rst_n = 1'b1;
        repeat (4) @(posedge clk_4x);

        // ── FADD: FP0=1.0, FP1=2.0 -> FP1 = 3.0 ─────────────────────────
        load_fp(0, EXT_1_0);
        load_fp(1, EXT_2_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h22)); // FADD
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_3_0, "FADD: 1.0 + 2.0 == 3.0");
        check(u_top.u_proto.u_regfile.fpsr_r[27:24] == 4'b0000,
              "FADD: condition codes clear for a positive nonzero result");

        // ── FSUB: FP0=1.0, FP1=3.0 -> FP1 = 3.0 - 1.0 = 2.0 ─────────────
        load_fp(0, EXT_1_0);
        load_fp(1, EXT_3_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h28)); // FSUB
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_2_0, "FSUB: 3.0 - 1.0 == 2.0");

        // ── FADD with a carry-out normalization: 0.5 + 0.5 = 1.0 ────────
        load_fp(0, EXT_0_5);
        load_fp(1, EXT_0_5);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h22)); // FADD
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_1_0, "FADD: 0.5 + 0.5 == 1.0 (carry-out renormalization)");

        // ── FADD: 1.0 + (-1.0) = 0.0, condition code Z set ──────────────
        load_fp(0, EXT_1_0);
        load_fp(1, EXT_N1_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h22)); // FADD
        check(u_top.u_proto.u_regfile.fp_r[1][94:0] == 95'h0, "FADD: 1.0 + (-1.0) == 0.0 (magnitude bits)");
        check(u_top.u_proto.u_regfile.fpsr_r[26] == 1'b1, "FADD: Z condition code set for a zero result");

        // ── FSUB: 1.5 - 0.5 = 1.0 (unequal exponents, real alignment) ───
        load_fp(0, EXT_0_5);
        load_fp(1, EXT_1_5);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h28)); // FSUB
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_1_0, "FSUB: 1.5 - 0.5 == 1.0 (exponent alignment)");

        // ── Negative result: FSUB 1.0 - 2.0 = -1.0, N condition code ────
        load_fp(0, EXT_2_0);
        load_fp(1, EXT_1_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h28)); // FSUB
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_N1_0, "FSUB: 1.0 - 2.0 == -1.0");
        check(u_top.u_proto.u_regfile.fpsr_r[27] == 1'b1, "FSUB: N condition code set for a negative result");

        // ── FMUL: 2.0 * 2.0 = 4.0 (product exactly at a power of 2) ─────
        load_fp(0, EXT_2_0);
        load_fp(1, EXT_2_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h23)); // FMUL
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_4_0, "FMUL: 2.0 * 2.0 == 4.0");

        // ── FMUL: 2.0 * 3.0 = 6.0 (product needs the [2,4) renormalization) ──
        load_fp(0, EXT_2_0);
        load_fp(1, EXT_3_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h23)); // FMUL
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_6_0, "FMUL: 2.0 * 3.0 == 6.0");

        // ── FMUL: 1.5 * 1.5 = 2.25 (no renormalization needed) ───────────
        load_fp(0, EXT_1_5);
        load_fp(1, EXT_1_5);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h23)); // FMUL
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_2_25, "FMUL: 1.5 * 1.5 == 2.25");

        // ── FMUL: sign combination, -1.0 * 3.0 = -3.0 ────────────────────
        load_fp(0, EXT_N1_0);
        load_fp(1, EXT_3_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h23)); // FMUL
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_N3_0, "FMUL: -1.0 * 3.0 == -3.0");
        check(u_top.u_proto.u_regfile.fpsr_r[27] == 1'b1, "FMUL: N condition code set for a negative product");

        // ── FMUL: 0.5 * 0.5 = 0.25 (both exponents below bias) ───────────
        load_fp(0, EXT_0_5);
        load_fp(1, EXT_0_5);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h23)); // FMUL
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_0_25, "FMUL: 0.5 * 0.5 == 0.25");

        // ── FDIV: 4.0 / 2.0 = 2.0 (exact, ratio >= 1 branch) ─────────────
        load_fp(0, EXT_2_0);
        load_fp(1, EXT_4_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h20)); // FDIV
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_2_0, "FDIV: 4.0 / 2.0 == 2.0");

        // ── FDIV: 3.0 / 2.0 = 1.5 (ratio < 1 branch on the mantissa divide) ──
        load_fp(0, EXT_2_0);
        load_fp(1, EXT_3_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h20)); // FDIV
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_1_5, "FDIV: 3.0 / 2.0 == 1.5");

        // ── FDIV: 6.0 / 2.0 = 3.0 ────────────────────────────────────────
        load_fp(0, EXT_2_0);
        load_fp(1, EXT_6_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h20)); // FDIV
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_3_0, "FDIV: 6.0 / 2.0 == 3.0");

        // ── FDIV: -6.0 / 2.0 = -3.0 (sign combination) ──────────────────
        load_fp(0, EXT_2_0);
        load_fp(1, {1'b1, EXT_6_0[94:0]}); // -6.0
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h20)); // FDIV
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_N3_0, "FDIV: -6.0 / 2.0 == -3.0");

        // ── FDIV: 1.0 / 0.0 -> signed Infinity, DZ flag set ──────────────
        load_fp(0, 96'h0); // +0.0
        load_fp(1, EXT_1_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h20)); // FDIV
        check(u_top.u_proto.u_regfile.fp_r[1] == {1'b0, 15'h7FFF, 16'h0, 64'h8000_0000_0000_0000},
              "FDIV: 1.0 / 0.0 == +Infinity");
        check(u_top.u_proto.u_regfile.fpsr_r[10] == 1'b1, "FDIV: DZ exception-status bit set for divide-by-zero");

        // ── FABS: |-3.0| = 3.0 (source in RX, result to RY) ──────────────
        load_fp(0, EXT_N3_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h18)); // FABS
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_3_0, "FABS: |-3.0| == 3.0");

        // ── Phase 9 regression: FABS genuinely occupies a real APU
        // pipeline slot now (Table 8-3: 38 real cycles, NOT zero) --
        // confirmed by observing it still IN FLIGHT (slotA_valid_r) right
        // after dispatch, well before its own real latency could have
        // already elapsed. Uses raw run_cycle (not dispatch(), which
        // itself waits for the pipeline to drain) specifically to catch
        // this mid-flight state.
        load_fp(0, EXT_N3_0);
        run_cycle(CIR_COMMAND, 1'b1, cmd_word(3'b000, 3'd0, 3'd1, 7'h18), rd); // FABS
        run_cycle(CIR_INSTRADDR, 1'b1, 32'h0000_3000, rd);
        run_cycle(CIR_RESPONSE, 1'b0, 32'h0, rd);
        check(u_top.u_proto.slotA_valid_r && u_top.u_proto.slotA_op_r == 7'h18,
              "Phase 9: FABS genuinely occupies slot A immediately after dispatch -- not instant on real silicon (Table 8-3)");
        wait_ticks_apu_drain();
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_3_0, "Phase 9: FABS eventually commits the same correct result: |-3.0| == 3.0");

        // ── FABS: |3.0| = 3.0 (already positive, no change in sign) ─────
        load_fp(0, EXT_3_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h18)); // FABS
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_3_0, "FABS: |3.0| == 3.0");

        // ── FNEG: -(2.0) = -2.0 ───────────────────────────────────────────
        load_fp(0, EXT_2_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h1A)); // FNEG
        check(u_top.u_proto.u_regfile.fp_r[1] == {1'b1, EXT_2_0[94:0]}, "FNEG: -(2.0) == -2.0");

        // ── FNEG: -(-1.0) = 1.0 (double negation) ────────────────────────
        load_fp(0, EXT_N1_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h1A)); // FNEG
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_1_0, "FNEG: -(-1.0) == 1.0");

        // ── FCMP: destination register (RY) is never written ────────────
        load_fp(0, EXT_2_0);
        load_fp(1, EXT_3_0); // dest pre-loaded with a sentinel value
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h38)); // FCMP
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_3_0, "FCMP: destination register FP1 is never written");

        load_fp(0, EXT_2_0);
        load_fp(1, EXT_2_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h38)); // FCMP: FP1(2.0) vs 2.0
        check(u_top.u_proto.u_regfile.fpsr_r[26] == 1'b1, "FCMP: Z condition code set when both operands are equal");

        load_fp(0, EXT_3_0);
        load_fp(1, EXT_2_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h38)); // FCMP: FP1(2.0) vs 3.0 -> 2.0-3.0<0
        check(u_top.u_proto.u_regfile.fpsr_r[27] == 1'b1, "FCMP: N condition code set when FPn < source");

        // ── FTST: tests the SOURCE operand alone, sets condition codes ───
        load_fp(0, 96'h0); // +0.0
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h3A)); // FTST +0.0
        check(u_top.u_proto.u_regfile.fpsr_r[26] == 1'b1, "FTST: Z condition code set for a zero source operand");

        load_fp(0, EXT_N1_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h3A)); // FTST -1.0
        check(u_top.u_proto.u_regfile.fpsr_r[27] == 1'b1, "FTST: N condition code set for a negative source operand");

        // ── FSQRT: sqrt(4.0) = 2.0 (even exponent, exact) ────────────────
        load_fp(0, EXT_4_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h04)); // FSQRT
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_2_0, "FSQRT: sqrt(4.0) == 2.0");

        // ── FSQRT: sqrt(1.0) = 1.0 (odd exponent path: exp(1.0)=0, even -- ─
        // use sqrt(2.25)=1.5 instead to exercise a non-trivial mantissa) ──
        load_fp(0, EXT_2_25);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h04)); // FSQRT
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_1_5, "FSQRT: sqrt(2.25) == 1.5");

        // ── FSQRT: sqrt(9.0) = 3.0 (odd real exponent: 9.0 has exp=3) ────
        load_fp(0, 96'h4002_0000_9000_0000_0000_0000); // 9.0
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h04)); // FSQRT
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_3_0, "FSQRT: sqrt(9.0) == 3.0 (odd-exponent path)");

        // ── FSQRT: sqrt(-4.0) -> NaN, OPERR set ──────────────────────────
        load_fp(0, {1'b1, EXT_4_0[94:0]}); // -4.0
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h04)); // FSQRT
        check(u_top.u_proto.u_regfile.fpsr_r[24] == 1'b1, "FSQRT: NAN condition code set for sqrt of a negative operand");
        check(u_top.u_proto.u_regfile.fpsr_r[13] == 1'b1, "FSQRT: OPERR exception-status bit set for sqrt of a negative operand");

        // ── FSQRT: sqrt(+0.0) = +0.0 ──────────────────────────────────────
        load_fp(0, 96'h0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h04)); // FSQRT
        check(u_top.u_proto.u_regfile.fp_r[1] == 96'h0, "FSQRT: sqrt(+0.0) == +0.0");

        // ── Phase 4d: SNAN detection ──────────────────────────────────────
        // Signaling NaN: exp=0x7FFF, mantissa leading fraction bit (bit62)
        // clear (Section 3.5.4) -- 0x8000000000000001 (bit63=1, bit62=0,
        // a nonzero fraction bit to distinguish from Infinity).
        load_fp(0, {1'b0, 15'h7FFF, 16'h0, 64'h8000_0000_0000_0001}); // sNaN
        load_fp(1, EXT_1_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h22)); // FADD
        check(u_top.u_proto.u_regfile.fpsr_r[14] == 1'b1, "Phase 4d: SNAN exception-status bit set for a signaling NaN input");
        check(u_top.u_proto.u_regfile.fpsr_r[7] == 1'b1, "Phase 4d: AEXC IOP bit set (SNAN contributes to IOP)");

        repeat (4) @(posedge clk_4x);

        // ── Phase 4d: INEX2 (inexact result) via FDIV 1.0/3.0 ────────────
        load_fp(0, {1'b0, 15'h3FFF + 15'd1, 16'h0, 64'hC000_0000_0000_0000}); // 3.0 (source)
        load_fp(1, EXT_1_0); // FPn (dest)
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h20)); // FDIV: FP1 = 1.0/3.0
        check(u_top.u_proto.u_regfile.fpsr_r[9] == 1'b1, "Phase 4d: INEX2 exception-status bit set for an inexact FDIV result");
        check(u_top.u_proto.u_regfile.fpsr_r[3] == 1'b1, "Phase 4d: AEXC INEX bit set (INEX2 contributes to AEXC INEX)");

        repeat (4) @(posedge clk_4x);

        // ── Phase 4d: OVFL via FADD pushing the exponent past 32767 ──────
        load_fp(0, {1'b0, 15'd32766, 16'h0, 64'h8000_0000_0000_0000});
        load_fp(1, {1'b0, 15'd32766, 16'h0, 64'h8000_0000_0000_0000});
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h22)); // FADD (doubles -> exponent+1 overflow)
        check(u_top.u_proto.u_regfile.fpsr_r[12] == 1'b1, "Phase 4d: OVFL exception-status bit set on exponent overflow");
        check(u_top.u_proto.u_regfile.fpsr_r[6] == 1'b1, "Phase 4d: AEXC OVFL bit set");
        check(u_top.u_proto.u_regfile.fp_r[1] == {1'b0, 15'h7FFF, 16'h0, 64'h8000_0000_0000_0000},
              "Phase 4d: overflowed result saturates to +Infinity");

        repeat (4) @(posedge clk_4x);

        // ── Phase 4d: UNFL (+ INEX2) via FMUL pushing the exponent below 1 ──
        load_fp(0, {1'b0, 15'd10, 16'h0, 64'hC000_0000_0000_0001}); // tiny, non-power-of-2 mantissa
        load_fp(1, {1'b0, 15'd10, 16'h0, 64'hC000_0000_0000_0001});
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h23)); // FMUL
        check(u_top.u_proto.u_regfile.fpsr_r[11] == 1'b1, "Phase 4d: UNFL exception-status bit set on exponent underflow");
        check(u_top.u_proto.u_regfile.fp_r[1] == 96'h0, "Phase 4d: underflowed result flushes to zero");

        repeat (4) @(posedge clk_4x);

        // ── Phase 4d: AEXC is sticky across separate, unrelated operations ──
        load_fp(0, 96'h0); // +0.0
        load_fp(1, EXT_1_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h20)); // FDIV 1.0/0.0 -> DZ
        check(u_top.u_proto.u_regfile.fpsr_r[4] == 1'b1, "Phase 4d: AEXC DZ bit set after a divide-by-zero");
        load_fp(0, EXT_1_0);
        load_fp(1, EXT_2_0);
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h22)); // an unrelated, exact FADD
        check(u_top.u_proto.u_regfile.fpsr_r[4] == 1'b1,
              "Phase 4d: AEXC DZ bit stays set (sticky) after a later, unrelated operation");
        check(u_top.u_proto.u_regfile.fpsr_r[10] == 1'b0,
              "Phase 4d: EXC DZ bit itself is NOT sticky -- cleared by the later, unrelated operation");

        // ── Phase 9: FMOVE (register-to-register, ext=$00) -- a real bug
        // fix. Previously this extension code fell into an unconditional
        // "no-op stub" fallback and silently did nothing at all (never
        // caught before since no existing test dispatched it and checked
        // the result); it's a real, defined instruction (Table 4-13:
        // "$00 FMOVE to FPn") that must copy the source register to the
        // destination, same as any other opclass-000 op, and now goes
        // through the real pipeline with its own genuine Table 8-3
        // latency (21 cycles).
        load_fp(0, EXT_N3_0);
        load_fp(1, EXT_1_0); // dest sentinel, != -3.0
        dispatch(cmd_word(3'b000, 3'd0, 3'd1, 7'h00)); // FMOVE FP0,FP1
        check(u_top.u_proto.u_regfile.fp_r[1] == EXT_N3_0, "Phase 9: FMOVE FP0,FP1 copies the source value (-3.0) to the destination");
        check(u_top.u_proto.u_regfile.fpsr_r[27] == 1'b1, "Phase 9: FMOVE sets the N condition code for a negative moved value");

        $display("---");
        $display("%0d passed, %0d failed", pass_count, fail_count);
        if (fail_count != 0) begin
            $display("APU TEST FAILED");
            $finish;
        end
        $display("APU TEST PASSED");
        $finish;
    end

endmodule
